import { createFileRoute, Link, notFound } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { ArrowRight, BriefcaseBusiness, CircuitBoard, FlaskConical, Monitor, ExternalLink } from 'lucide-react';
import { consultaEspecialidades, consultaAlbumes, consultaOportunidades } from '@/lib/consultas';
import { identidadEspecialidades } from '@/lib/identidad-especialidades';
import { enlaceSeguro } from '@/lib/media';
import { Button } from '@/components/ui/button';
import { Reveal } from '@/components/site/reveal';
import { ErrorContenido } from '@/components/site/estado-ruta';
import { NoEncontrado } from '@/components/site/no-encontrado';
export const Route=createFileRoute('/especialidad/$slug')({
 loader:async({context,params})=>{const [especialidades]=await Promise.all([context.queryClient.ensureQueryData(consultaEspecialidades),context.queryClient.ensureQueryData(consultaAlbumes),context.queryClient.ensureQueryData(consultaOportunidades)]);const especialidad=especialidades.find(e=>e.slug===params.slug);if(!especialidad)throw notFound();return {especialidad}},
 head:({loaderData})=>{const e=loaderData?.especialidad;const title=`${e?.nombre??'Especialidad'} — Técnica 3 Avellaneda`;const description=e?.resumen??'Formación técnica, prácticas y oportunidades.';return {meta:[{title},{name:'description',content:description},{property:'og:title',content:title},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'},...(e?.imagen?.startsWith('https:')?[{property:'og:image',content:e.imagen},{name:'twitter:image',content:e.imagen}]:[])]}},
 errorComponent:ErrorContenido,notFoundComponent:NoEncontrado,component:Especialidad,
});
function Especialidad(){
 const {especialidad:e}=Route.useLoaderData();const {data:albumes}=useSuspenseQuery(consultaAlbumes);const {data:oportunidades}=useSuspenseQuery(consultaOportunidades);
 const identidad=identidadEspecialidades[e.slug];if(!identidad)return <NoEncontrado/>;
 const Icono=e.slug==='informatica'?Monitor:e.slug==='electronica'?CircuitBoard:FlaskConical;
 const fotos=albumes.filter(a=>a.categoria.toLowerCase()===e.slug||a.slug===e.slug).flatMap(a=>a.fotos).filter(f=>f.tipo!=='video').slice(0,4);
 const vacantes=oportunidades.filter(o=>o.especialidad_slug===e.slug);
 return <div className={identidad.clase}>
 <section className="relative isolate overflow-hidden bg-institutional text-institutional-foreground"><img src={e.imagen||identidad.imagen} alt={e.imagenAlt||e.nombre} className="absolute inset-0 -z-20 size-full object-cover" fetchPriority="high"/><div className="specialty-cover absolute inset-0 -z-10"/><div className="contenedor py-12 sm:py-20 lg:py-24"><nav aria-label="Ruta de navegación" className="flex flex-wrap gap-2 text-xs text-institutional-foreground/80"><Link to="/">Inicio</Link><span>/</span><Link to="/especialidades">Especialidades</Link><span>/</span><span>{e.nombreCorto}</span></nav><Icono className="mt-12 size-9 text-institutional-accent"/><p className="technical-label mt-5 text-institutional-accent">{identidad.etiqueta}</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight sm:text-5xl lg:text-6xl">{e.nombre}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-institutional-foreground/90">{e.resumen}</p><Button asChild variant="secondary" className="mt-8"><Link to="/contacto">Consultar por la especialidad<ArrowRight/></Link></Button></div></section>
 <section className="contenedor grid gap-10 py-14 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)] lg:py-20"><Reveal><p className="technical-label text-specialty">Del aula al proyecto</p><h2 className="mt-4 text-3xl font-semibold">Lo que hacemos</h2><p className="mt-5 whitespace-pre-line leading-relaxed text-muted-foreground">{e.practicas||e.resumen}</p><Button asChild variant="link" className="mt-5 px-0"><Link to="/galeria">Ver proyectos y prácticas<ArrowRight/></Link></Button></Reveal><Reveal className="border-l-4 border-specialty pl-6"><p className="technical-label text-specialty">Proyección profesional</p><h2 className="mt-4 text-3xl font-semibold">Salida laboral</h2><p className="mt-5 whitespace-pre-line leading-relaxed text-muted-foreground">{e.salidaLaboral}</p></Reveal></section>
 {fotos.length>0&&<section className="bg-surface py-12"><div className="contenedor"><p className="technical-label text-specialty">En nuestro taller</p><h2 className="mt-4 text-3xl font-semibold">Aprendizajes que se ven</h2><div className={`mt-8 grid gap-5 ${e.slug==='informatica'?'md:grid-cols-2':'sm:grid-cols-2 lg:grid-cols-3'}`}>{fotos.map((f,i)=><Reveal key={f.src} delay={i*60} className="media-reveal"><figure><img src={f.src} alt={f.alt} loading="lazy" className="aspect-[4/3] w-full rounded-lg object-cover"/><figcaption className="mt-3 text-sm text-muted-foreground">{f.alt}</figcaption></figure></Reveal>)}</div></div></section>}
 <section className="contenedor py-14 lg:py-20"><div className="flex items-center gap-3"><BriefcaseBusiness className="size-6 text-specialty"/><p className="technical-label text-specialty">El próximo paso</p></div><h2 className="mt-4 text-3xl font-semibold">Trabajo y pasantías</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{vacantes.map(o=>{const enlace=enlaceSeguro(o.enlace);return <article key={o.id} className="rounded-lg border border-border border-t-4 border-t-specialty bg-card p-6"><p className="technical-label text-specialty">{o.tipo==='pasantia'?'Pasantía':'Empleo'}{o.organizacion&&` / ${o.organizacion}`}</p><h3 className="mt-3 text-xl font-semibold">{o.titulo}</h3><p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">{o.descripcion}</p>{o.requisitos&&<p className="mt-4 whitespace-pre-line text-sm"><strong>Requisitos:</strong> {o.requisitos}</p>}{o.fecha_cierre&&<p className="mt-4 text-xs text-muted-foreground">Cierre: {o.fecha_cierre.split('-').reverse().join('/')}</p>}{enlace?<Button asChild className="mt-5"><a href={enlace} target="_blank" rel="noopener noreferrer">Ver oportunidad<ExternalLink/></a></Button>:<Button asChild variant="outline" className="mt-5"><Link to="/contacto">Consultar<ArrowRight/></Link></Button>}</article>})}</div>{vacantes.length===0&&<div className="mt-6 border-l-4 border-specialty bg-surface p-6"><p className="text-muted-foreground">No hay oportunidades publicadas por el momento.</p><Button asChild variant="link" className="mt-3 px-0"><Link to="/contacto">Consultar a la escuela<ArrowRight/></Link></Button></div>}</section>
 </div>
}