/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CapacitacionesRouteImport } from './routes/capacitaciones'
import { Route as CentroDeEstudiantesRouteImport } from './routes/centro-de-estudiantes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAvisosRouteImport } from './routes/_authenticated/admin.avisos'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin.calendario'
import { Route as AuthenticatedAdminCapacitacionesRouteImport } from './routes/_authenticated/admin.capacitaciones'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminCentroRouteImport } from './routes/_authenticated/admin.centro'
import { Route as AuthenticatedAdminGaleriaRouteImport } from './routes/_authenticated/admin.galeria'
import { Route as AuthenticatedAdminInstitucionalRouteImport } from './routes/_authenticated/admin.institucional'
import { Route as AuthenticatedAdminMateriasRouteImport } from './routes/_authenticated/admin.materias'
import { Route as AuthenticatedAdminMensajesRouteImport } from './routes/_authenticated/admin.mensajes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacionesRoute = CapacitacionesRouteImport.update({
  id: '/capacitaciones',
  path: '/capacitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroDeEstudiantesRoute = CentroDeEstudiantesRouteImport.update({
  id: '/centro-de-estudiantes',
  path: '/centro-de-estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAvisosRoute =
  AuthenticatedAdminAvisosRouteImport.update({
    id: '/avisos',
    path: '/avisos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCapacitacionesRoute =
  AuthenticatedAdminCapacitacionesRouteImport.update({
    id: '/capacitaciones',
    path: '/capacitaciones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCentroRoute =
  AuthenticatedAdminCentroRouteImport.update({
    id: '/centro',
    path: '/centro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGaleriaRoute =
  AuthenticatedAdminGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstitucionalRoute =
  AuthenticatedAdminInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMateriasRoute =
  AuthenticatedAdminMateriasRouteImport.update({
    id: '/materias',
    path: '/materias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMensajesRoute =
  AuthenticatedAdminMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/centro-de-estudiantes': typeof CentroDeEstudiantesRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/capacitaciones': typeof AuthenticatedAdminCapacitacionesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/centro': typeof AuthenticatedAdminCentroRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/institucional': typeof AuthenticatedAdminInstitucionalRoute
  '/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/centro-de-estudiantes': typeof CentroDeEstudiantesRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
  '/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/capacitaciones': typeof AuthenticatedAdminCapacitacionesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/centro': typeof AuthenticatedAdminCentroRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/institucional': typeof AuthenticatedAdminInstitucionalRoute
  '/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/centro-de-estudiantes': typeof CentroDeEstudiantesRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/avisos': typeof AuthenticatedAdminAvisosRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/capacitaciones': typeof AuthenticatedAdminCapacitacionesRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/centro': typeof AuthenticatedAdminCentroRoute
  '/_authenticated/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/_authenticated/admin/institucional': typeof AuthenticatedAdminInstitucionalRoute
  '/_authenticated/admin/materias': typeof AuthenticatedAdminMateriasRoute
  '/_authenticated/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/centro-de-estudiantes'
    | '/contacto'
    | '/galeria'
    | '/institucional'
    | '/materias'
    | '/admin'
    | '/admin/avisos'
    | '/admin/calendario'
    | '/admin/capacitaciones'
    | '/admin/categorias'
    | '/admin/centro'
    | '/admin/galeria'
    | '/admin/institucional'
    | '/admin/materias'
    | '/admin/mensajes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/centro-de-estudiantes'
    | '/contacto'
    | '/galeria'
    | '/institucional'
    | '/materias'
    | '/admin/avisos'
    | '/admin/calendario'
    | '/admin/capacitaciones'
    | '/admin/categorias'
    | '/admin/centro'
    | '/admin/galeria'
    | '/admin/institucional'
    | '/admin/materias'
    | '/admin/mensajes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/centro-de-estudiantes'
    | '/contacto'
    | '/galeria'
    | '/institucional'
    | '/materias'
    | '/_authenticated/admin'
    | '/_authenticated/admin/avisos'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/capacitaciones'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/centro'
    | '/_authenticated/admin/galeria'
    | '/_authenticated/admin/institucional'
    | '/_authenticated/admin/materias'
    | '/_authenticated/admin/mensajes'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisosRoute: typeof AvisosRoute
  CalendarioRoute: typeof CalendarioRoute
  CapacitacionesRoute: typeof CapacitacionesRoute
  CentroDeEstudiantesRoute: typeof CentroDeEstudiantesRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  InstitucionalRoute: typeof InstitucionalRoute
  MateriasRoute: typeof MateriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitaciones': {
      id: '/capacitaciones'
      path: '/capacitaciones'
      fullPath: '/capacitaciones'
      preLoaderRoute: typeof CapacitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-de-estudiantes': {
      id: '/centro-de-estudiantes'
      path: '/centro-de-estudiantes'
      fullPath: '/centro-de-estudiantes'
      preLoaderRoute: typeof CentroDeEstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/avisos': {
      id: '/_authenticated/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AuthenticatedAdminAvisosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/capacitaciones': {
      id: '/_authenticated/admin/capacitaciones'
      path: '/capacitaciones'
      fullPath: '/admin/capacitaciones'
      preLoaderRoute: typeof AuthenticatedAdminCapacitacionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/centro': {
      id: '/_authenticated/admin/centro'
      path: '/centro'
      fullPath: '/admin/centro'
      preLoaderRoute: typeof AuthenticatedAdminCentroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galeria': {
      id: '/_authenticated/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/institucional': {
      id: '/_authenticated/admin/institucional'
      path: '/institucional'
      fullPath: '/admin/institucional'
      preLoaderRoute: typeof AuthenticatedAdminInstitucionalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/materias': {
      id: '/_authenticated/admin/materias'
      path: '/materias'
      fullPath: '/admin/materias'
      preLoaderRoute: typeof AuthenticatedAdminMateriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensajes': {
      id: '/_authenticated/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AuthenticatedAdminMensajesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAvisosRoute: typeof AuthenticatedAdminAvisosRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminCapacitacionesRoute: typeof AuthenticatedAdminCapacitacionesRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminCentroRoute: typeof AuthenticatedAdminCentroRoute
  AuthenticatedAdminGaleriaRoute: typeof AuthenticatedAdminGaleriaRoute
  AuthenticatedAdminInstitucionalRoute: typeof AuthenticatedAdminInstitucionalRoute
  AuthenticatedAdminMateriasRoute: typeof AuthenticatedAdminMateriasRoute
  AuthenticatedAdminMensajesRoute: typeof AuthenticatedAdminMensajesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAvisosRoute: AuthenticatedAdminAvisosRoute,
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminCapacitacionesRoute: AuthenticatedAdminCapacitacionesRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminCentroRoute: AuthenticatedAdminCentroRoute,
  AuthenticatedAdminGaleriaRoute: AuthenticatedAdminGaleriaRoute,
  AuthenticatedAdminInstitucionalRoute: AuthenticatedAdminInstitucionalRoute,
  AuthenticatedAdminMateriasRoute: AuthenticatedAdminMateriasRoute,
  AuthenticatedAdminMensajesRoute: AuthenticatedAdminMensajesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisosRoute: AvisosRoute,
  CalendarioRoute: CalendarioRoute,
  CapacitacionesRoute: CapacitacionesRoute,
  CentroDeEstudiantesRoute: CentroDeEstudiantesRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  InstitucionalRoute: InstitucionalRoute,
  MateriasRoute: MateriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
