/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CapacitacionesRouteImport } from './routes/capacitaciones'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as MateriasRouteImport } from './routes/materias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacionesRoute = CapacitacionesRouteImport.update({
  id: '/capacitaciones',
  path: '/capacitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/calendario': typeof CalendarioRoute
  '/capacitaciones': typeof CapacitacionesRoute
  '/institucional': typeof InstitucionalRoute
  '/materias': typeof MateriasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/institucional'
    | '/materias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/institucional'
    | '/materias'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/calendario'
    | '/capacitaciones'
    | '/institucional'
    | '/materias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  CalendarioRoute: typeof CalendarioRoute
  CapacitacionesRoute: typeof CapacitacionesRoute
  InstitucionalRoute: typeof InstitucionalRoute
  MateriasRoute: typeof MateriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitaciones': {
      id: '/capacitaciones'
      path: '/capacitaciones'
      fullPath: '/capacitaciones'
      preLoaderRoute: typeof CapacitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  CalendarioRoute: CalendarioRoute,
  CapacitacionesRoute: CapacitacionesRoute,
  InstitucionalRoute: InstitucionalRoute,
  MateriasRoute: MateriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
